# Test with vscode rest client extention

GET http://localhost:5000/course/comments?course=ECE344

###

DELETE http://localhost:5000/course/comments?comment_id=3415146804509036774


###

POST http://localhost:5000/course/comments
Content-Type: Application/json


{
    "username": "test",
    "course": 1,
    "text": "test comment"
}