# Create pr workflow to build and deploy to heroku
name: CICD
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install npm dependencies
        run: npm install
        working-directory: ./Education_Pathways/frontend

      - name: Install pip dependencies
        run: pip install -r requirements.txt
      # Run backend tests
      - name: Run backend tests
        run: |
          python -m tests.test_app
        working-directory: ./Education_Pathways

      - name: Run frontend tests
        run: |
          npm test
        working-directory: ./Education_Pathways/frontend
  heroku-pull-request-deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: ep-allstars-pr-${{ github.event.number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.action == 'closed' && 1 || 0 }}
          ref: ${{ github.event.action != 'closed' && github.head_ref || '' }}

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: sindhu.parth@gmail.com
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          justlogin: true

      - name: Create Heroku app
        # if: github.event.action == 'opened'
        run: heroku apps:create ${{ env.HEROKU_APP_NAME }} # --team=my-team

      # - name: Add Heroku app to pipeline
        # if: github.event.action == 'opened'
        # run: heroku pipelines:add my-pipeline --app=${{ env.HEROKU_APP_NAME }} --stage=development

      # - name: Copy environment variables to Heroku app
        # if: github.event.action == 'opened'
        # run: |
          # heroku config --shell --app=my-development-app > .env
          # cat .env | tr '\n' ' ' | xargs heroku config:set --app=${{ env.HEROKU_APP_NAME }}

      - name: Add Heroku remote
        run: heroku git:remote --app=${{ env.HEROKU_APP_NAME }}

      - name: Push to Heroku
        run: git push heroku ${{ github.head_ref }}:master --force

      - name: Add comment to PR
        if: github.event.action == 'opened'
        run: |
          gh pr comment ${{ github.event.number }} --body '[Heroku app](https://dashboard.heroku.com/apps/${{ env.HEROKU_APP_NAME }}): https://${{ env.HEROKU_APP_NAME }}.herokuapp.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Destroy Heroku app
        if: github.event.action == 'closed'
        run: heroku apps:destroy --app=${{ env.HEROKU_APP_NAME }} --confirm=${{ env.HEROKU_APP_NAME }}
